config/routes.rb
Rails.application.routes.draw do
  
  #devise_for :users
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  
  root'products#index'
  
  resources :products, only:[:index, :show]
  
  namespace :admin do 
    resources :products
    resources :orders
  end 
  
  resource :cart, only:[:show] do   #單數的resource建立的路徑會比較簡單,沒有id區分,也沒有index, cart單複數沒差
   post 'add', path:'add/:id'
   get 'checkout'
  end
  
  resources :orders, except:[:destroy]
  
end

app/models/cart.rb
class Cart
    
    attr_reader :items
    
    def serialize
        
        all_items= @items.map do |item|
           {"item_id" => item.item_id, "quantity" => item.quantity}
         end
    
      {"cart" => all_items}
      
    end
    
    def self.build_from_hash(hash)
     if hash.nil?
         all_items = []
     else
       all_items = hash["cart"].map {|item|
        CartItem.new(item["item_id"], item["quantity"])
       }
     end 
      
      new(all_items)
      #cc=Cart.new(all_items)等於上一行
      #return cc        等於上上一行                                         
    end                                                   
                                                    
    def initialize(items=[])   
     @items = items
    end
    
    def total_price 
      #  sum=0
      #  @items.each do |item|
      #      sum +=item.price
        @items.inject(0) {|sum, item| sum + item.price}    
    end
    
    def add_item(id)
        item = @items.find {|item| item.item_id == id}
        
        if item
            item.increment_quantity 
        else
            @items << CartItem.new(id)
        end
        
    end
    
    def empty?
        return @items.empty?  #return 可以不寫
    end
    
    #def items
    #    return @items  #return 可以不寫
   # end                # attr_reader :items  等於那三行,  還有兩種 寫入 跟 可讀可寫
                       
    def has_item?
        !empty?
    end
    
    
    
    
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

    before_action :initialize_cart
    
    def show
    end
    
    def checkout
        @order=Order.new
        @token=Braintree::ClientToken.generate
    end
    
  
    def add
      product = Product.find_by(id: params[:id]) 
      if product
         # add to car    
           @cart.add_item(product.id)
            session[:cart]= @cart.serialize
           flash[:notice]= "商品 #{product.name} 已加入購物車"
      else
       flash[:notice] = '無此商品'
 
      end
     
      redirect_to :back
    end
  
    #private
   # def initialize_cart
   #     @cart = Cart.build_from_hash(session[:cart])
  #  end  抽到application_controller
  
    
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart_table.html.erb
<table class='table'>
    <thead>
        <tr>
            <td> 商品名稱 </td>
            <td> 單價 </td>
            <td> 數量</td>
            <td> 小計 </td>
        </tr>
    </thead>
    <tbody>
        <% @cart.items.each do |item| %>
        <tr>
            <td><%= item.product.name %></td>
            <td><%= item.product.price %></td>
            <td><%= item.quantity %></td>
            <td><%= item.price %></td>
        </tr>
        <% end %>
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3"> 總計 </td>
            <td> <%=@cart.total_price %> </td>
        </tr>
    </tfoot>
</table>

app/views/carts/checkout.html.erb
<%= content_for :head_js do %>
<script src="https://js.braintreegateway.com/v2/braintree.js"></script>
<% end %>

<h1> 結帳 </h1>

<%=render 'carts/cart_table' %>
<hr />

 <%= simple_form_for(@order) do |f| %>
    <%= f.input :recipient, label:false, placeholder:'收件者' %>
    <%= f.input :address, label:false, placeholder:'收件地址' %>
    <%= f.input :tel, label:false, placeholder:'聯絡電話' %>
    <%= f.input :email, label:false, placeholder:'聯絡信箱' %>
    <%= f.input :will_receive_edm, label:'是否願意收到優惠方案' %>
    <hr />
    <div id="dropin"></div>
    <hr />
    <%= f.submit class:'btn btn-danger'%>
 <% end %>
 


<script>
// We generated a client token for you so you can copy and paste this code
// and try it out right away. See the section below to generate your
// own client token.
var clientToken = "<%= @token %>"

braintree.setup(clientToken, "dropin", {
  container: "dropin"
});
</script>

app/views/carts/show.html.erb
<h1> 購物車 </h1>

<%=render 'cart_table' %>
<%=link_to '繼續選購', products_path, class:'btn btn-primary'%>

<%=link_to '結帳', checkout_cart_path, class:'btn btn-danger' unless @cart.empty? %>