config/routes.rb
Rails.application.routes.draw do
  
  #devise_for :users
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  
  root'products#index'
  
  resources :products, only:[:index, :show]
  
  namespace :admin do 
    resources :products
    resources :orders
  end 
  
  resource :cart, only:[:show] do   #單數的resource建立的路徑會比較簡單,沒有id區分,也沒有index, cart單複數沒差
   post 'add', path:'add/:id'
   get 'checkout'
  end
  
  resources :orders, except:[:destroy]
  
end

app/models/product.rb
class Product < ActiveRecord::Base
    
    validates :name, presence: true
    
    default_scope {where(is_deleted: false)}  #所有撈出來的資料都是標記為未刪除的
    
    scope :available, -> { where(is_online: true)}
    
    def destroy
     self.is_deleted = true
     save #= self.save
    end
    
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController #ApplicationController
    
    #layout 'admin' #改繼承自BASECONTROLLER
    #before_action :authenticate_user! #幫後台做些管理權限 devise 套件送的方法 一定要登入 才能進入後台
    
    def index
        #@products = Product.page(params[:page]).per(10).where(is_deleted:false) #因為有裝KAMINAMI,直接用分頁功能
                                         #判斷是否被標記為未刪除的才顯示   
                                         #因為太醜了 所以在Model寫個scope 預設撈出來的就是未標記刪除的
       @products = Product.page(params[:page]).per(10)                   
                                                            
    end                                                
    
    
    def new
        @product = Product.new
    end
    
    def create
        @product = Product.new(product_params)
        if @product.save
            redirect_to admin_products_path, notice:'新增商品成功'
        else
            render :new
        end
    end
    
    def show
        @product = Product.find_by(id: params[:id])
    end
    
    def edit
        @product = Product.find_by(id: params[:id])
    end
    
    def update
        @product = Product.find_by(id: params[:id])
        if @product.update_attributes(product_params)
            redirect_to  admin_products_path, notice:'編輯商品成功'
        else
            render :new
        end
    end
    
    
    def destroy
        @product = Product.find_by(id: params[:id])
        
        #@product.destroy  方法一
        #@product.is_deleted = true
        #@product.save                方法二
        
        @product.destroy  #複寫destroy方法在 model內 包入了@product.is_deleted =true @product.save 的方法
        redirect_to admin_products_path, notice: '商品已刪除'
    end
    
    
    
    private
    def product_params
        params.require(:product).permit(:name, :description, :price, :is_online)
    end
    
    
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    
    
    before_action :initialize_cart
    
    def index
        #@products = Product.where(is_online: true) #這邊不需要.all因為後面有where了 
        @products = Product.available  #定義在model裡面 scope available, -> { where(is_online: ture)}

    end
    
   
    

    
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
    
    def online_status(item)
        if item.is_online
            "已上線"
        else
            "未上線"
        end
    end
    
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%=simple_form_for([:admin, @product]) do |f| %>

  <%= f.input :name, label:false, placeholder:'商品名稱' %>
  <%= f.input :description,label:false, placeholder:'商品描述' %>
  <%= f.input :price, label:false, placeholder:'商品價錢' %>
  <%= f.input :is_online %>

  
  <%= f.submit @product.new_record? ? "新增商品" : "編輯商品", class:'btn btn-danger' %>
 
<% end %>

app/views/admin/products/edit.html.erb
<h1> 編輯商品：<%= @product.name %> </h1>
<br>
<%=render 'form' %>
<br>
<%= link_to '返回詳細資料', admin_product_path(@product), class: 'btn btn-info' %>
<%=link_to '返回商品列表', admin_products_path, class: 'btn btn-success' %>

app/views/admin/products/index.html.erb
<h1> 商品列表 </h1> 
<%=link_to'新增商品', new_admin_product_path, class: 'btn btn-primary' %>
<hr />
<div class="row">
  <div class="col-md-3"> 分類 </div>
  <div class="col-md-9">
      <table class="table">
          <thead>
              <tr>
                <td>商品名稱</td>
                <td>售價</td>
                <td>狀態</td>
                <td>詳細資料</td>
                <td>編輯商品</td>
                <td>刪除</td>
              </tr>
          </thead>
          <tbody>
              <% @products.each do |product| %>
              <tr>
                <td> <%= product.name %>  </td>
                <td> <%= product.price %> </td>
                <td> <%= online_status(product) %> </td> <!-- 寫在helper的方法 -->
                <td> <%= link_to '詳細資料', admin_product_path(product), class: 'btn btn-xs btn-success' %> </td>
                <td> <%= link_to '編輯商品', edit_admin_product_path(product), class: 'btn btn-xs btn-warning' %> </td>
                <td> <%= link_to '刪除', admin_product_path(product), method: :delete, data:{confirm:'確定嗎?'}, 
                        class: 'btn btn-xs btn-danger' if can?( :manage, product) %> </td>
              </tr>
              <% end %>
          </tbody>
      </table>
  </div>
</div>

app/views/admin/products/new.html.erb
<h1> 新增商品 </h1>
<br>
<%=render 'form' %>
<br>
<%=link_to '返回商品列表', admin_products_path, class:'btn btn-success' %>

app/views/admin/products/show.html.erb
<h1> 商品名稱：<%= @product.name %> </h1>

<table class="table">
    <thead>
        <tr>
            <th> 商品描述 </th>
            <th> 商品價格 </th>
            <th> 商品狀態 </th>
        </tr>
    </thead>
    
    <tbody>
        <tr>
            <td> <%= @product.description %> </td>
            <td> <%= @product.price %> </td>
            <td> <%= online_status(@product) %> </td>
        </tr>
    </tbody>
</table>
<br>
    <%= link_to '編輯商品', edit_admin_product_path(@product), class: 'btn btn-warning' %>
    <%= link_to '返回商品列表', admin_products_path, class: 'btn btn-success' %>
    
    