config/routes.rb
Rails.application.routes.draw do
  
  #devise_for :users
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  
  root'products#index'
  
  resources :products, only:[:index, :show]
  
  namespace :admin do 
    resources :products
    resources :orders
  end 
  
  resource :cart, only:[:show] do   #單數的resource建立的路徑會比較簡單,沒有id區分,也沒有index, cart單複數沒差
   post 'add', path:'add/:id'
   get 'checkout'
  end
  
  resources :orders, except:[:destroy]
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  
    private
    def initialize_cart
        @cart = Cart.build_from_hash(session[:cart])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_flash_message.html.erb
<% flash.each do |flash_type, message| %>
  <div class="alert alert-success alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <%= message %>
</div>
<% end %>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">My Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
       
         
       
        <%=render 'navbar_cart' %>
        
        <% if user_signed_in? %>
          
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%=current_user.email %> <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            
            <% if current_user.is_admin? %>
             <li> <%=link_to '商品管理', admin_products_path %> </li>
             <li> <%=link_to '訂單管理', admin_orders_path %> </li>
            <% end %>
            
            <li> <%=link_to '編輯', edit_user_registration_path %> </li>
          
            <li class="divider"></li>
            <li><%= link_to '登出',destroy_user_session_path, method: :delete %> </li>
          </ul>
        </li>
        
        <% else %>
        
         <li><%= link_to '註冊', new_user_registration_path %></li>
         <li><%= link_to '登入', new_user_session_path %></li>
         
        <% end %>
        
        
        
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/application/_navbar_admin.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">管理系統</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Email <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">登出</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/application/_navbar_cart.html.erb
<li>
    <%=link_to cart_path do %>
     購物車
     <% if @cart && @cart.has_item?  %>
       <span class="badge"> <%=@cart.items.count %> </span>
     <% end %>
    <% end %>
</li>

<%# if @cart.items.count > 0 %> 

<%#<li> <%#=link_to "購物車 <span class ='badge'> #{@cart.items.count} </span>".html_safe, cart_path %> <%#</li>

<%# else %>

<%#<li> <%#=link_to "購物車", cart_path %> <%#</li>
<%# end %>